# Generated by Django 5.2.7 on 2025-10-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('entrada_estoque', models.DateField(auto_now_add=True)),
                ('saida_estoque', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='almoxarifado.categoriaproduto')),
            ],
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='categorias', to='almoxarifado.produto'),
        ),
    ]
